"""Add recognition_file_path columns to AudioFile

Revision ID: 4be21280fce4
Revises: bd4c5bd772fd
Create Date: 2024-11-16 14:04:52.242892

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4be21280fce4'
down_revision = 'bd4c5bd772fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audio_files', schema=None) as batch_op:
        batch_op.add_column(sa.Column('recognition_file_path', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audio_files', schema=None) as batch_op:
        batch_op.drop_column('recognition_file_path')

    # ### end Alembic commands ###
