"""Make file_path nullable

Revision ID: bf8663cbc5d1
Revises: 4be21280fce4
Create Date: 2024-11-16 15:24:06.803229

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf8663cbc5d1'
down_revision = '4be21280fce4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audio_files', schema=None) as batch_op:
        batch_op.alter_column('file_path',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
        batch_op.drop_column('recognition_file_path')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audio_files', schema=None) as batch_op:
        batch_op.add_column(sa.Column('recognition_file_path', sa.VARCHAR(length=200), nullable=True))
        batch_op.alter_column('file_path',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)

    # ### end Alembic commands ###
